spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        username: username
        password: password
        server-addr: ip:8848
      config:
        username: username
        password: password
        server-addr: ip:8848
        file-extension: yaml
  config:
    import:
      - nacos:${spring.application.name}?refreshEnabled=true
